### ISSUE TITLE
Navigatiebalk

### ISSUE THREAD

**Issue by AbelLykens** [DeBitcoinShow/debitcoinshow.github.io#14]
Wie kan een navigatiebalk maken?

**Comment by BlackBeltBob** [comment]
Wat voor een type navigatie balk willen we? Multi-level? Responsive en web-first? Iets met een hamburgermenu in dat laatste geval?

**Comment by AbelLykens** [comment]
Denk wat simpels, maar wel rekening houdend met mobiel ja? Smal = hamburger? :hamburger:

**Comment by BlackBeltBob** [comment]
Een hamburgermenu is een icoontje van drie horizontale streepjes. Wordt eigenlijk overal gebruikt als "hierin hebben we het menu gestopt". Met wat jQuery en een flexbox layout kan je tegenwoordig heel snel en makkelijk een responsive menu maken. Let wel, dat is dan vooral zonder multi-level, als je dat wil wordt de code al snel een stuk groter.

**Comment by AbelLykens** [comment]
Ja precies. Ik bedoelde, "als de site smal wordt, dan naar hamburgermenu?".

Hou het simpel zou ik zeggen. Alleen-CSS als voorkeur? ;)

**Comment by BlackBeltBob** [comment]
Even afgezien van de vorm, wat moet de inhoud worden? Aangezien de pagina nu gewoon 1 enkele page is. Willen we algemene pagina's over:
1. Bitcoin, 
2. de presentatoren, 
3. De eventuele gasten die langsgeweest zijn?
4. De afleveringen (waarbij gezocht kan worden op shownotes, titels, etc)

**Comment by AbelLykens** [comment]
Ja dat laat ik grotendeels aan de hosts ;). Zodra die een username hebben (#6 ) dan taggen we ze wel hier ;)

**Comment by BlackBeltBob** [comment]
Ik zag trouwens een mooie oplossing voor een hamburger menu zonder dat je moelilijk met jquery hoeft te doen. Je voegt een checkbox toe met een label, en kunt dan de checkbox zelf op display:none zetten. zodra je hem vinkt kan je de css van de nav erin aanpassen. Zie: [hier](https://codepen.io/daviddarnes/pen/mDBLJ)

**Comment by BlackBeltBob** [comment]
@JWBurgers: Heb jij al een idee over of en wat je in een eventueel menu zou willen plaatsen? Overzicht van alle afleveringen, stukje over de hosts, etc?

**Comment by ghost** [comment]
Beste, ik heb een navigatiebalk geïmplementeerd, zie https://github.com/DeBitcoinShow/debitcoinshow.github.io/pull/35

**Comment by JWBurgers** [comment]
Deze stond nog open. Op zich is de site zo klein dat een navigatiebalk mij wat overkill lijkt.
