### ISSUE TITLE
Hoofd-URL (debitcoinshow.nl) overzetten naar GitHub-hosting

### ISSUE THREAD

**Issue by AbelLykens** [DeBitcoinShow/debitcoinshow.github.io#21]
[ ] Site OK zoals hij nu is op github
[ ] DNS aanpassen
[ ] HTTPS aanzetten

**Comment by AbelLykens** [comment]
Nu Jan access heeft (krijgt), kunnen we hiermee verder kijken.

**Comment by AbelLykens** [comment]
Nieuw plan van aanpak. Credentials zijn gedeeld.

1) TTL DNS-records ASAP verlagen naar 5 minuten, nu 4 uur. Minimaal 4 uur wachten na deze stap (voorstel om een dag te wachten)
2) Github pages instellen op debitcoinshow.nl
3) DNS aanpassen
4) Testen. HTTPS instellen.
5) TTL terug naar 4 uur.

OK Boris / @JWBurgers ?

**Comment by JWBurgers** [comment]
Ha Abel,

 

Dank je hiervoor. Dit lijkt me dit prima. De datum maakt mij niet zoveel uit. Wat zullen we doen?

 

Verder, mijn uitnodiging voor de repository was verlopen. Zou je me nog een keer willen uitnodigen?

 

Groeten,

 

Jan-Willem

**Comment by AbelLykens** [comment]
Top laten we zaterdag de 2e overgaan dan :+1:

**Comment by AbelLykens** [comment]
DNS TTL aangepast naar 900 seconden ter voorbereiding.

**Comment by AbelLykens** [comment]
Gelukt! Met HTTPS!
