### ISSUE TITLE
Suggestie: pagina met links naar bitcoin projecten

### ISSUE THREAD

**Issue by BlackBeltBob** [DeBitcoinShow/debitcoinshow.github.io#25]
Een beetje een pagina zoals die van lopp, waar je een overzicht ziet van interessante projecten die op Bitcoin gebouwd worden/zijn. Liefst relevant voor nederland en de show.

1. Openstaande Bips als Taproot/schnorr/mast
2. (Hobby)Projecten van bitcoiners in het telegramkanaal
3. Second layer ontwikkelingen als LN of Liquid.

**Comment by Sndrkr** [comment]
Deze issue neem ik zonder problemen mee in https://github.com/DeBitcoinShow/debitcoinshow.github.io/pull/35.

**Comment by ghost** [comment]
Ik zou adviseren dat dit een soort blog vorm zou aannemen, waarbij we voor een platform kiezen dat goed embeddable is in de website. Zo hoeven we geen aanpassingen te maken aan de bron code om nieuwe updates toe te voegen, maar kunnen we simpelweg het desbetreffende platform up to date houden.

**Comment by JWBurgers** [comment]
Ik snap de motivatie voor de suggestie, alleen dat gaat het doel van de site een beetje voorbij. We willen de site het liefst zo klein mogelijk en concreet houden.

Mocht iemand zelf zo'n site willen opzetten en onderhouden kunnen we dat wel delen met de gemeenschap.
