### ISSUE TITLE
Klink- en linkbare headers

### ISSUE THREAD

**Issue by AbelLykens** [DeBitcoinShow/debitcoinshow.github.io#26]
Als de headers klikbaar zijn (html anchor) dan kunnen we een link sturen met specifiek paginadeel.

**Comment by BlackBeltBob** [comment]
Even een snelle blik op de html toont dat alle sections al een id hebben, dus dan kunnen we daar heen linken toch?
Voorbeeld: https://debitcoinshow.github.io/#Doe_mee

**Comment by AbelLykens** [comment]
Ja precies. Maar dan nog de headers klikbaar maken (op andere sites zie je wel eens dat er dan zo'n ketting-icoon bijkomt bij hover).

**Comment by BlackBeltBob** [comment]
Begrijp ik je goed als ik dat vertaal naar: "Bij hoveren komt er een icoon die, als je erop klikt een link op het clipboard zet naar die header op die pagina"? Zodat je makkelijk een link kan maken naar die header als buitenstaander.

**Comment by AbelLykens** [comment]
Een `a href="#ONDERDEEL"` om de H1 zou genoeg zijn. Zodat je rechtsklik-linkcopy kan doe :). Copy naar clipboard is misschien overkill :)

**Comment by BlackBeltBob** [comment]
zal ik anders die fix doen? Dan loop ik alle headers even langs, en dan vul ik als #ONDERDEEL de id van de section in.

**Comment by AbelLykens** [comment]
Ja do yo thing :smile:

**Comment by BlackBeltBob** [comment]
ik heb hem in een pull request zitten.

**Comment by BlackBeltBob** [comment]
Ik heb de styling van de A eraf gehaald, want dat leek me onlogisch. Je hebt nu gewoon een link om de h1 zitten van class="hidden" waarop je kan klikken en eventueel met rechtsklikken kan copyen.

**Comment by AbelLykens** [comment]
gelukt dus
