### ISSUE TITLE
SSL-probleem door BTCPayserver

### ISSUE THREAD

**Issue by AbelLykens** [DeBitcoinShow/debitcoinshow.github.io#4]
De include van btcpayserver laat een alert zien in browsers

**Comment by AbelLykens** [comment]
Boris moet SSL fixen op de btcpayserver ;)

**Comment by AbelLykens** [comment]
#22 lost dit deels op (bij eerste load). Nog wel melding bij doen van betaling.

**Comment by aerctic** [comment]
Lijkt erop dat de SSL weer vernieuwd moet worden? https://pay.gamekings.tv:49392/api/v1/invoices

**Comment by JWBurgers** [comment]
We hebben dit helemaal weggehaald.
