### ISSUE TITLE
Meetup info aanpassen

### ISSUE THREAD

**Issue by johanf85** [DeBitcoinShow/debitcoinshow.github.io#44]
Aangezien een meetup aanstaande is, kan ie ook op de DBS site worden toegevoegd. Ook de ticketprijs staat nog op 5 euro op de site.
Misschien is het mogelijk automatisch te embedden mbv een iframe oid. Deze info vond ik: https://answers.pagecloud.com/help/meetup

**Comment by JWBurgers** [comment]
Inmiddels alles bijgewerkt.
