### ISSUE TITLE
Het logo is wat wazig en groot in kB

### ISSUE THREAD

**Issue by johanf85** [DeBitcoinShow/debitcoinshow.github.io#45]
Het viel me op dat het logo wat wazig is op debitcoinshow.nl . Denk dat dit komt omdat het logobestand groot van afmeting is en dat de browser het niet mooi terugschaalt. 

In de CSS zag ik dat het logo een max-width had van 693 px. Daarom heb ik het logo verkleind in photoshop naar 693 px en daarnaast opgeslagen met png-8 ipv png-24. Hierdoor is werd de grootte van het logo 44kb ipv de huidige 122 kb, dus laadt dan sneller. 

Ik kon geen pull request doen voor het logo omdat het ik het niet kon uploaden. Het logo dat ik heb verkleind is hier:

[https://github.com/johanf85/debitcoinshow.github.io/blob/master/Images/Logo_De_Bitcoin_Show.png](https://github.com/johanf85/debitcoinshow.github.io/blob/master/Images/Logo_De_Bitcoin_Show.png)  

Een svg vector logo zou het ook oplossen, maar dan heb je wel de vector bronbestanden nodig. 
  
Het ziet er nu zo uit bij mij (Mac, chrome): 

![](https://user-images.githubusercontent.com/43075793/121570263-01a19e80-ca22-11eb-9e61-3b6c480facc2.png)

Dit is het logo dat ik heb verkleind:

(gek genoeg lijken de kleuren nu af te wijken, maar dat komt volgens mij door de screencapture die omzet naar jpg)

![Logo_De_Bitcoin_Show.png](https://github.com/johanf85/debitcoinshow.github.io/blob/master/Images/Logo_De_Bitcoin_Show.png?raw=true)

**Comment by JWBurgers** [comment]
Inmiddels de pull request geaccepteerd. Dank!
