### ISSUE TITLE
Suggestie: 

### ISSUE THREAD

**Issue by johanf85** [DeBitcoinShow/debitcoinshow.github.io#47]
Ik merk dat de DBS website niet vaak wordt geüpdate. Kan natuurlijk een tijdgebrek zijn of prioriteiten elders leggen. 

Als de github wijze niet bevalt kun je ook voor Wordpress kiezen oid. Ik moet wel zeggen dat ik het wel leuk vind dat het via Github is, want dan kan iedereen suggesties doen. Uiteindelijk levert dat ook weer ideeën en 'engagement' op. 

Even een suggestie om wat makkelijker de site te beheren. Ik denk dat het handiger is om jekyll te gebruiken. Link: https://jekyllrb.com/docs/github-pages/

Dit heeft namelijk het voordeel dat je pagina's in Markdown kan schrijven, die worden daarna automatisch in html omgezet. Markdown is iets makkelijker te gebruiken, zeker in combinatie met een CKeditor plugin (zie onder)

Ook kun je dan  includes gebruiken in een pagina, bijvoorbeeld {% include header.html %}. 

Je maakt dan edits aan alleen het deel van de pagina dat je wil wijzigen en je hoeft niet alles door te scrollen. 

Je plaatst deze includes in een map genaamd \_includes.

En 2:

Als je Jekyll gebruikt en de inhoud van pagina's in Markdown zet, kun je ook deze  chrome plugin voor WYSIWYG editor  in Google Chrome gebruiken. Zie: [https://chrome.google.com/webstore/detail/github-writer/diilnnhpcdjhhkjcbdljaonhmhapadap](https://chrome.google.com/webstore/detail/github-writer/diilnnhpcdjhhkjcbdljaonhmhapadap) 

WYSIWYG = what you is what you get

Deze plugin zet automatisch alle bewerkingsvelden om in een makkelijkere editor, dan hoef je niet zelf te markdown'en. Ik kan markdown goed lezen, maar ik vind het nutteloos om markdown helemaal zelf te schrijven. 

Het venster waarin ik dit in schrijf heeft geeft dan  buttons voor opmaak, zie screenshot: 

![](https://user-images.githubusercontent.com/43075793/123851868-fdc7b480-d91b-11eb-81d3-0518891a321c.png)

**Comment by JWBurgers** [comment]
Bedankt voor de goede suggesties. 

Op zich komen we er zo wel redelijk mee uit de voeten, dus laat het even voor wat is. Mochten we het onszelf wat makkelijker willen maken kunnen we deze suggestie volgen.
